# Generated by Django 3.2.23 on 2024-01-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_rename_price_accommodation_price_per_night'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='price_per_night',
            new_name='price',
        ),
    ]
