# Generated by Django 3.2.23 on 2024-01-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_rename_price_per_night_accommodation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
