# Generated by Django 3.2.23 on 2024-01-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_auto_20240102_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='price',
            new_name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='capacity',
        ),
    ]
